update .babelrc with a fix for issue 65
update .babelrc with fix for `TypeError: require.ensure is not a function` issue. Tracked in issue 65.

Fixes: 
https://github.com/btholt/complete-intro-to-react/issues/65